### ISSUE TITLE
Error installing LibYAML

### ISSUE THREAD

**Issue by restaurantt** [haxpor/Potatso#100]
follow the steps
1.git clone https://github.com/haxpor/Potatso.git or for faster using less time in cloning git clone https://github.com/haxpor/Potatso.git --depth=1
2.cd Potatso
3.git submodule update --init to update git submodule
4.pod install to pull down dependencies into our project

<img width="563" alt="2018-07-31 11 23 40" src="https://user-images.githubusercontent.com/5440798/43435852-6b6c9a5a-94b4-11e8-9e00-78fbae71e8f6.png">
and open the potatso.xcworkspace
<img width="729" alt="2018-07-31 11 26 45" src="https://user-images.githubusercontent.com/5440798/43435897-a5ac5a66-94b4-11e8-97d9-6f0fe07c0e60.png">
please help me

**Comment by haxpor** [comment]
Make sure you successfully install `YAML-Framework` via git submodule. Check such library in `Library/YAML-Framework` whether you see anything or not. If not, try to remove cloned Potatso directory, connect to SS on your machine, then start over.

Related to #97 #98

**Comment by restaurantt** [comment]
succeed, i use VPN instead of SS

**Comment by huayu0723** [comment]
I found a solution myself and here are the details:
1. start a HTTP proxy application, like Charles, and add a rule to map http://pyyaml.org to  https://pyyaml.org
2. set the http proxy before running 'pod install' in command line, like 'export http_proxy=http://127.0.0.1:8888'
