### ISSUE TITLE
PacketTunnel can not get Potatso.sharedGroupIdentifier

### ISSUE THREAD

**Issue by FBSENDER** [haxpor/Potatso#11]
when PacketTunnel is running, it can not get correct Potatso.sharedGroupIdentifier.

Here is the file and code:

PotatsoManager.m

+ (NSString *) sharedGroupIdentifier {
    return [NSString stringWithFormat:@"group.%@", [[NSBundle mainBundle] bundleIdentifier]];
}

**Comment by haxpor** [comment]
I re-visit this, and it relates to #13 .
#13 is fixed, and above code is changed to fixed one which solved the problem.

Thanks again for reporting! :)
