### ISSUE TITLE
Module 'Crashlytics' not found

### ISSUE THREAD

**Issue by ZNBmm** [haxpor/Potatso#117]

**Comment by wangyingbo** [comment]
Profile文件里没有加这个库，添加一下就ok了。pod 'Crashlytics', '~> 3.10.7'

**Comment by ZNBmm** [comment]
> Profile文件里没有加这个库，添加一下就ok了。pod 'Crashlytics', '~> 3.10.7'

你的可以跑起来了吗

**Comment by wangyingbo** [comment]
> > Profile文件里没有加这个库，添加一下就ok了。pod 'Crashlytics', '~> 3.10.7'
> 
> 你的可以跑起来了吗

已经跑起来了。。

**Comment by ZNBmm** [comment]
> > > Profile文件里没有加这个库，添加一下就ok了。pod 'Crashlytics', '~> 3.10.7'
> > 
> > 
> > 你的可以跑起来了吗
> 
> 已经跑起来了。。
可以加个微信私聊吗

**Comment by wangyingbo** [comment]
> > > > Profile文件里没有加这个库，添加一下就ok了。pod 'Crashlytics', '~> 3.10.7'
> > > 
> > > 
> > > 你的可以跑起来了吗
> > 
> > 
> > 已经跑起来了。。
> > 可以加个微信私聊吗

加我qq吧，2532084725
