### ISSUE TITLE
 Showing Recent Issues Command failed due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by Jasoncoool** [haxpor/Potatso#12]
hi,haxpor
How to solve this problem?
![2017-02-23 4 01 49](https://cloud.githubusercontent.com/assets/13887641/23249908/9bef25ae-f9e1-11e6-9fd8-d25d7c08b66d.png)
![2017-02-23 4 02 06](https://cloud.githubusercontent.com/assets/13887641/23249913/a0ad6f56-f9e1-11e6-98e2-42dea4c07c14.png)

**Comment by haxpor** [comment]
Did you build against ios 10.3? If so, it doesnt support yet. Please stick with 10.2.

**Comment by Jasoncoool** [comment]
I just build with 10.2below.

**Comment by Jasoncoool** [comment]
Xcode : Version 8.0 (8A218a)

**Comment by Jasoncoool** [comment]
Xcode Version 8.2.1 (8C1002) build success !

**Comment by haxpor** [comment]
@Jasoncoool great! thanks for letting me know! I close this for now :)
