### ISSUE TITLE
No podspec found for `CallbackURLKit` in `./Library/CallbackURLKit`

### ISSUE THREAD

**Issue by shaibow** [haxpor/Potatso#15]
I've cloned the project and 
`git submodule update --init`
and tons of error appeared ! I think the reason is because @icodesign has removed it's project.
and when i'm trying to `pod install` i get this error 
[!] No podspec found for `CallbackURLKit` in `./Library/CallbackURLKit`

**Comment by haxpor** [comment]
Hey! This has been fixed before in #9 .
I suspect that you're still on the old version when you pulled down. Please make sure you pull down the latest one.

`CallbackURLKit` doesn't depend on original author. You can take a look at `.gitmodules` file, there should be only one that depends on him which is `shadowsocks-libev`.

**Comment by icodesign** [comment]
`CallbackURLKit` is not a must-be dependency. You can remove it and the related code. You can also find it on `https://github.com/phimage/CallbackURLKit`.

**Comment by shaibow** [comment]
Thanks, That works !
