### ISSUE TITLE
Should add more logs when connecting VPN

### ISSUE THREAD

**Issue by willbin** [haxpor/Potatso#19]
I have config my own app id and run this project on my device, but after configuring one proxy and tapping 'connect', the VPN config in 'Settings - VPN' was added, but the VPN connect failed, and no related logs show in Xcode console.

So please make a config document to check my config is right or not, or add more logs to track the connect process.

Thanks.

**Comment by AliThink** [comment]
I encontered the same issue. Your problem solved?

**Comment by willbin** [comment]
@AliThink 
Sorry, I forgot the detail about this issue and finally compile succeeded.
But in general, yours can work well by following these tips.

Some tips for compiling this project: 
0. Use Xcode 8, not Xcode9
1. manual code sign method.
2. regenerate the entitlements files within Xcode.
3. other configs in the Apple develop site which you should know.
