### ISSUE TITLE
是否修改了添加GEOIP就会断开隧道的BUG？

### ISSUE THREAD

**Issue by aishuidedabai** [haxpor/Potatso#23]

**Comment by mumusa** [comment]
请问如何用真机调试呢，项目里有多个bundle id，怎么配置呢，个人没有配置过extension的经验？希望得到回复

**Comment by aishuidedabai** [comment]
他有例子，你改下即可

**Comment by mumusa** [comment]
在haxpor的repos和icodesign的repos里面都没有找到https://github.com/ifusernameif/test ，是不是这个，作者貌似都删掉了

**Comment by mumusa** [comment]
因为之前是直接下载的zip方式，改用git 命令后用在根据haxpor的提示可以了。谢谢

**Comment by aishuidedabai** [comment]
例子很清楚了。。

**Comment by lampchop** [comment]
我也有这个问题， GEOIP设置以后就断开。

**Comment by so898** [comment]
你们会出现这个问题的原因在于项目缺少必要的 GeoLite2-Contry.mmdb 文件
这个文件在 Potatso 项目中并没有提供
相关文件可以在 http://dev.maxmind.com/zh-hans/geoip/geoip2/geolite2-%E5%BC%80%E6%BA%90%E6%95%B0%E6%8D%AE%E5%BA%93/ 这里下载

**Comment by aishuidedabai** [comment]
能否具体一点，这个文件下载后放在哪个地方，直接放吗，要不要填写相应的ID

**Comment by so898** [comment]
https://github.com/haxpor/Potatso/blob/master/PotatsoLibrary/Manager.swift#L135

请查看这段代码

**Comment by aishuidedabai** [comment]
确实少这个文件，但是添加了还是在一到两分钟奔溃，能告知下吗

**Comment by aishuidedabai** [comment]
问题已找到谢谢

**Comment by aishuidedabai** [comment]
我关闭Error 了

**Comment by haxpor** [comment]
@so898 @aishuidedabai Do you think I should download that "GeoLite2-Country.mmdb" file and put it into Potatso project and thus into the project ?

**Comment by so898** [comment]
@haxpor I think you should do it. 
Without this file, the GEOIP rule will never work. 
If someone set the GEOIP rule, the PacketTunnel will shut down without any useful log.

**Comment by willbin** [comment]
@haxpor You have NOT added that file yet.
And I took days to resolve this issue, and finally I found this "closed issue".

**Comment by haxpor** [comment]
@willbin finally added it now. 👌

**Comment by CacheTechLtd** [comment]
@so898 请问，为什么我无法运行这个项目呢？真机调试会在`open static let sharedManager = Manager()` 抛出异常。iOS 10.3.3
