### ISSUE TITLE
vpn does not work in iOS 10.3.2?

### ISSUE THREAD

**Issue by WiiliamChik** [haxpor/Potatso#26]
after update my iphone system to 10.3.2,  the network is unavailable when i connect vpn with potatso. everything is alright before 10.3.2.

**Comment by haxpor** [comment]
Is there any log error during debugging from Xcode, or logs from Logs section of the app itself?
I'm using `10.3.2` and there's no problem.

**Comment by WiiliamChik** [comment]
i am wrong, there is no problem.
