### ISSUE TITLE
iOS10.3.2 Can't connect VPN

### ISSUE THREAD

**Issue by vki** [haxpor/Potatso#29]
@haxpor @so898 

Xcode version 8.3(8E162)
iOS version 10.2.3
iPhone mode : iphone 6 plus 
macOS version : 10.12.4 (16E195)

the sharedGroupIdentifier was changed, but was can't connect vpn

![img_0709](https://user-images.githubusercontent.com/538786/27011214-d4701200-4ee9-11e7-824d-bd2e251266ce.PNG)
<img width="376" alt="2017-06-11 9 07 12" src="https://user-images.githubusercontent.com/538786/27011219-f08c20f0-4ee9-11e7-9c7d-4a3ccfe2063d.png">

**Comment by so898** [comment]
You need to set the App Groups of the PacketTunnel as the same as the Potatso. (They are in last pic of your post)
So the VPN process could read the configuration files in the App Groups directory.

BTW, if you want to use the today widget, you should change set the App Groups of the TodayWidget in the same way.

**Comment by vki** [comment]
@so898 
Thanks,  it's work for me !
But Why the Github Project set PacketTunnel keychain share add .tunnel 
<img width="860" alt="2017-06-12 8 09 46" src="https://user-images.githubusercontent.com/538786/27015658-796cf2f8-4f46-11e7-9998-049637cbdfdf.png">
