### ISSUE TITLE
ShadowPath issue

### ISSUE THREAD

**Issue by lusfold** [haxpor/Potatso#3]
![image](https://cloud.githubusercontent.com/assets/13173319/22075331/96f25448-dde6-11e6-890d-75de93adf8f2.png)

How can i solve this problem ?

**Comment by haxpor** [comment]
Make sure you execute `git submodule update --init` at the root directory of project.

**Comment by haxpor** [comment]
Thank you @lusfold for updating and closing the issue! I didn't have time to check it out yet though.
