### ISSUE TITLE
When build,shadowsocks-libev/libipset/set/inspection.c not found

### ISSUE THREAD

**Issue by bi7jta** [haxpor/Potatso#32]
no such file or directory: '/work_studio/demo_iosproxy/Potatso-Utility/Library/ShadowPath/ShadowPath/shadowsocks-libev/libipset/set/inspection.c' 

Then I pull new version of shadowsocks-libev  https://github.com/shadowsocks1/shadowsocks-libev
Then build,it error:
clang: error: no such file or directory: '/work_studio/demo_iosproxy/Potatso-Utility/Library/ShadowPath/ShadowPath/shadowsocks-libev/src/tls1.2_ticket.c'
clang: error: no input files

I found a version with tls1.2_ticket.c 
https://github.com/shadowsocks-plus/shadowsocks-libev

build it error:
unknown type name obfs

Who can help me? Thanks

**Comment by bi7jta** [comment]
I got it, because it is a soft link! 
Close this issue.

**Comment by bi7jta** [comment]
ld: framework not found YAML

**Comment by iWECon** [comment]
Can you tell me how you solved this problem?
I also met the OBFS bug.

**Comment by chuheridangwu** [comment]
Can you tell me how you solved this problem?
I also met the OBFS bug.
