### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by jokefaker** [haxpor/Potatso#35]
error meesage：
/Potatso/Library/ShadowPath/ShadowPath/shadowsocks-libev/src/rule.h:46:5: Unknown type name 'pcre'

step:
1.manual clone git submodules;
2.run pod install;
3.run carthage update;
4.build;

env:
macOS 10.12.5
Xcode 8.3.3
pod 1.1.1
carthage 0.23.0

**Comment by JeansHuang** [comment]
[JeansHuang/Potatso](https://github.com/JeansHuang/Potatso)  Work for Xcode9.1 iOS11.1 Swift3.2

**Comment by haxpor** [comment]
@jokefaker I guess it's about un-finished git-module pulling or some sort, just guess. But please try again as I think it's minor issue that could be easily resolve. Please re-open if you still face this issue. Thanks!

FYI: Project now updated to newer version of xcode and cocoapod. I don't think this is an issue for your case. But just in case.
