### ISSUE TITLE
Update project to depend on HTTPS instead of SSH for all dependencies

### ISSUE THREAD

**Issue by haxpor** [haxpor/Potatso#38]
Due to a report long ago, and #37 , it's better idea to switch to fetch remote repositories (dependencies) from HTTPS instead as some users might not set up SSH key with their github account yet. This should get rid of redundant same problem users've reported so far.

**Comment by godwar10** [comment]
how to Configure git -ssh
my blog http://www.jianshu.com/p/c01fbf5e4d1c
