### ISSUE TITLE
这个报错是语法问题吗，swift才接触不久

### ISSUE THREAD

**Issue by godwar10** [haxpor/Potatso#39]
API.SWIFT 类

var rules: [Rule] = []
        if let parsedObject = Mapper<Rule>().mapArray(JSONArray: rulesJSON as! [[String : Any]]){
            rules.append(contentsOf: parsedObject)
        }

报错 ：initiallzer for conditional binding must have Optional type ,not '[Rult]'

if let parsedObject = Mapper<T>().mapArray(JSONArray: JSONToMap as! [[String : Any]]){
                    return .success(parsedObject)
                }

报错 ：initializer for conditional binding must have Optional type .not [T]

**Comment by Sky891028** [comment]
怎么解决的？

**Comment by Sky891028** [comment]
pod 'ObjectMapper', '2.2.2'
 降低这个版本就不用处理swift错误了
