### ISSUE TITLE
运行报错问题

### ISSUE THREAD

**Issue by godwar10** [haxpor/Potatso#41]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'App Group Capabilities may not be correctly configured for your project, or your appGroupIdentifier may not match your project settings. Check Project->Capabilities->App Groups. Three checkmarks should be displayed in the steps section, and the value passed in for your appGroupIdentifier should match the setting in your project file.'
时不时出现，我添加了3个证书了。
总是出现这个问题大家有没有遇到的。

**Comment by haxpor** [comment]
The identifier value in code is taken from [Potatso.m](https://github.com/haxpor/Potatso/blob/master/PotatsoBase/Potatso.m#L15). You have to make sure this value is correctly configured in Project->Capabilities->App Groups like the image below

![screen shot 2017-08-08 at 6 19 29 pm](https://user-images.githubusercontent.com/673757/29067766-7fc74416-7bf9-11e7-8fef-98be3c8be126.png)

**Comment by godwar10** [comment]
ok now. The perfect solution to my problem

**Comment by haxpor** [comment]
Good to hear! Then I close this issue for now. Thanks.
