### ISSUE TITLE
Error about git submodule update --init  

### ISSUE THREAD

**Issue by JoviZT** [haxpor/Potatso#45]
Run the fitst step "git submodule update --init " , my result is this
`Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:phimage/CallbackURLKit.git' into submodule path '/Users/zt/Documents/WorkSpace/Potatso/Library/CallbackURLKit' failed
Failed to clone 'Library/CallbackURLKit'. Retry scheduled
Cloning into '/Users/zt/Documents/WorkSpace/Potatso/Library/Eureka'...
Permission denied (publickey).
fatal: Could not read from remote repository.`

**Comment by haxpor** [comment]
The problem the project pull down remote repository via `ssh`. You need to set up your github's SSH key. See [here](https://github.com/haxpor/Potatso/issues/37#issuecomment-319947054).

I close this now, feel free to reopen if still facing problem.

**Comment by JoviZT** [comment]
Thx
