### ISSUE TITLE
API.swift get "Initializer for conditional binding must have Optional type, not '[Rule]'" error

### ISSUE THREAD

**Issue by wenewzhang** [haxpor/Potatso#46]
i have update to Xcode 9,try compile Potatso and get the error:
Initializer for conditional binding must have Optional type, not '[Rule]'
`            if (JSONToMap != nil) {
                if let parsedObject = Mapper<T>().mapArray(JSONArray: JSONToMap as! [[String : Any]]){
                    return .success(parsedObject)
                }
            }`

Thanks

**Comment by wenewzhang** [comment]
i delete the  if let ,change to let,
compile success,

**Comment by adteven** [comment]
swift convert on xcode9？

**Comment by wenewzhang** [comment]
if let parsedObject = Mapper<T>().mapArray(JSONArray: JSONToMap as! [[String : Any]]){ return .success(parsedObject) } 
change to 
let parsedObject = Mapper<T>().mapArray(JSONArray: JSONToMap as! [[String : Any]])
 return .success(parsedObject)

**Comment by adteven** [comment]
xcode  9
/Users/cuiboqiang/Desktop/workspace/git/sswork/Potatso2/Pods/Realm/Realm/ObjectStore/src/results.cpp:281:28: No viable overloaded '='

**Comment by wenewzhang** [comment]
pod update fix this

**Comment by JeansHuang** [comment]
[JeansHuang/Potatso](https://github.com/JeansHuang/Potatso)  Work for Xcode9.1 iOS11.1 Swift3.2

**Comment by haxpor** [comment]
Updated to support xcode 9.2. Feel free to re-open this issue if you still face the problem.
