### ISSUE TITLE
项目无法编译

### ISSUE THREAD

**Issue by bolee** [haxpor/Potatso#47]
你们确定都能在swift3可以编译么？总是编译错误999+，都是版本版本不兼容，导致引入模块失败

**Comment by JeansHuang** [comment]
[JeansHuang/Potatso](https://github.com/JeansHuang/Potatso)  Work for Xcode9.1 iOS11.1 Swift3.2

**Comment by haxpor** [comment]
@bolee I'm sure. Potatso and its child targets are compiled with either swift version `3.0`, or `3.2`. And all Pods are compiled against swift version `3.2`. The project is updated to support newer version of xcode (9.2) now, you might want to try. It should be ok.

**Comment by bolee** [comment]
@haxpor OK,I'll try again,Thanks.
