### ISSUE TITLE
"Failed to save configuration" with Xcode9

### ISSUE THREAD

**Issue by willbin** [haxpor/Potatso#49]
The log said:

`[NEVPNManager saveToPreferenc:337  Failed to save configuration: Error Domain=NEVPNErrorDomain Code=5 "permission denied" UserInfo={NSLocalizedDescription=permission denied}
`

Only happens when using Xcode9 to compile.
In Xcode8 it will show "add vpn" pop-up.

**Comment by so898** [comment]
You could try to switch Network Extension(**Project -> Capabilities**) off/on, then Xcode will rebuild the entitlements file.
I have the same issue when I deal with the NEKit, I do this and reinstall the app, then this problem fixed.

**Comment by willbin** [comment]
@so898 It works now. Thanks.
