### ISSUE TITLE
Build failed due to an error while compiling a Cocoapod dependency, how can I handle with it? Thanks.

### ISSUE THREAD

**Issue by tommyxu97** [haxpor/Potatso#51]
File: Pods/Realm/results.cpp
Xcode says "No viable overloaded '='", but how come there can exist an error with an open-source dependency?
Xcode 9 , pod 1.2.1
Is it possible that something wrong with the version of my Xcode? Thanks.
<img width="1131" alt="2017-11-22 1 49 00" src="https://user-images.githubusercontent.com/20267885/33088177-d9a00b86-cf27-11e7-849b-74932e1d6280.png">

**Comment by aishuidedabai** [comment]
Xcode9 is  not surpport，u should change Xcode8

**Comment by tommyxu97** [comment]
@aishuidedabai OK, I will try it. Thanks!

**Comment by aishuidedabai** [comment]
是reaml还未适配，等它适配了再pod install即可

**Comment by tommyxu97** [comment]
@aishuidedabai  今天下午详细google了一下这个问题，在Realm的issues里面看到了也有人碰到这个问题，貌似是用最新的版本是可以编译通过的
![](https://github.com/realm/realm-cocoa/issues/5369)

**Comment by JeansHuang** [comment]
用Xcode8.2，妥妥的，How to Build Project 照做搞定

**Comment by tommyxu97** [comment]
@JeansHuang OK, thanks
