### ISSUE TITLE
swift compiler Error

### ISSUE THREAD

**Issue by wz812180** [haxpor/Potatso#52]
Xcode Version:8.3.3 Swift Version:3

At Potatso/Base/Row/RequestEventRow.swift line 14
Type RequestEventRow does not conform to protocol 'RowType'
Type RequestEventRow does not conform to protocol 'Taggable'
Type RequestEventRow does not conform to protocol 'TypedRowType'
Type RequestEventRow does not conform to protocol 'BaseRowType'
Generic type 'Row' specialized with too many type parameters(got 2,but expected 1)

At Potatso/Base/RequestEventRow.swift line 17
'super' members cannnoe be referenced in a root class

At Potatso/Base/RequestEventRow.swift line 18
Use of unresolved idenyifier 'displayValueFor'

And the same errors happend in Potatso/Base/Row/ProxyRow.swift,it look like swift version error.

**Comment by JeansHuang** [comment]
Use Xcode8.2

**Comment by wz812180** [comment]
@JeansHuang Ok,thank you.9.1->8.3.3->8.2,crazy!

**Comment by wz812180** [comment]
@JeansHuang I have checked xcode 8.2,it allways the same error

**Comment by wz812180** [comment]
Where's the type 'Row' be defined?

**Comment by JeansHuang** [comment]
[JeansHuang/Potatso](https://github.com/JeansHuang/Potatso)  Work for Xcode9.1 iOS11.1 Swift3.2

**Comment by haxpor** [comment]
@wz812180 I updated to support xcode9.2. The issue should be resolved. Feel free to re-open if you still face the issue.
