### ISSUE TITLE
已编译通过，支持Xcode9.1 iOS11.1 Swift3.2

### ISSUE THREAD

**Issue by JeansHuang** [haxpor/Potatso#55]
[JeansHuang/Potatso](https://github.com/JeansHuang/Potatso)  Work for Xcode9.1 iOS11.1 Swift3.2

**Comment by InjoyDeng** [comment]
编译错误，提示
no such file or directory: '/Users/Injoy/Desktop/Potatso/Library/ShadowPath/ShadowPath/shadowsocks-libev/libipset/set/inspection.c'

**Comment by JeansHuang** [comment]
@InjoyDeng clone 我 fork的。
https://github.com/JeansHuang/Potatso

1.git clone --recursive https://github.com/JeansHuang/Potatso.git
2.carthage update
build support Xcode9.1 iOS11.1 Swift3.2

**Comment by luanma** [comment]
Hi @InjoyDeng ,

I tried  to clone your reporstory ,but got below error ,

Cloning into 'Library/CallbackURLKit'...
Permission denied (publickey).
fatal: Could not read from remote repository.

I can clone other projects from GitHub. Is there any steps I missed.

Cheers
Lee

**Comment by InjoyDeng** [comment]
@luanma 
This is not my reporstory.

Maybe it'll help you.
https://help.github.com/articles/error-permission-denied-publickey/

**Comment by luanma** [comment]
@InjoyDeng 

Cool, that helps. my environment issue. Resolved. 

Cheers,

**Comment by haxpor** [comment]
Closed due to issue resolved. Thanks
