### ISSUE TITLE
Unable to satisfy the following requirements:  - `KeychainAccess` required by `Podfile`

### ISSUE THREAD

**Issue by victorcf** [haxpor/Potatso#59]
When I do "Pod install", I get this:

Analyzing dependencies
Fetching podspec for `Aspects` from `./Library/Aspects/`
Fetching podspec for `CallbackURLKit` from `./Library/CallbackURLKit`
Fetching podspec for `Eureka` from `./Library/Eureka/`
Fetching podspec for `ICSMainFramework` from `./Library/ICSMainFramework/`
[!] Unable to satisfy the following requirements:

- `KeychainAccess` required by `Podfile`
- `KeychainAccess` required by `Podfile`
- `KeychainAccess` required by `Podfile`
- `KeychainAccess` required by `Podfile`
- `KeychainAccess (= 3.0.1)` required by `Podfile.lock`

None of your spec sources contain a spec satisfying the dependencies: `KeychainAccess, KeychainAccess (= 3.0.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

Would you help me? My pod version is 1.3.1. MacOS version is 10.13.2. Thank you.

**Comment by haxpor** [comment]
This is likely your pod's repo has outdated source thus there is no information about `KeychainAccess`. I tried to `pod deintegrate` on my end, and `pod install` again with success.

Please just `pod repo update` to update your pod's repo then start over again.

**Comment by victorcf** [comment]
"pod repo update" works for me. Thank you.
