### ISSUE TITLE
compile with free apple id

### ISSUE THREAD

**Issue by victorcf** [haxpor/Potatso#60]
Hi, when I try to compile with my apple id which I do not pay 99 dollars to Apple, I get "Code Signing Error: Your account does not have sufficient permissions to modify containers." So is it possible to complile and run it with a free apple id? If it is, what change should I make? Thank you.

**Comment by haxpor** [comment]
Please got to Capabilities->iCloud and also see other places as well. Check that everything is fine, and no red text or error showing up. If you see red text, or error, try to turn such capability off then on.

As well, make sure you added your Apple ID account in Xcode->Preferences->Accounts and selected it as a team in General->Signing tab.

**Comment by victorcf** [comment]
Thank you. I have this red spot I cannot remove. 

![2017-12-29 5 58 53](https://user-images.githubusercontent.com/5397161/34434583-085080fc-ecc2-11e7-97a8-8d4276cf89e2.png)

I have already turn off every item in Capabilities.

![2017-12-29 6 00 29](https://user-images.githubusercontent.com/5397161/34434615-35197242-ecc2-11e7-9489-b5ac8b3f83b2.png)

**Comment by victorcf** [comment]
iCloud is not in the picture, because I don't have this item for the free apple id.

**Comment by haxpor** [comment]
From your capability image, it seems `Network extension` is not available. This will be a blocker. I guess you might have to have developer account.

**Comment by victorcf** [comment]
OK, thank you for you answer.
