### ISSUE TITLE
修改bundle id打包成功后闪退

### ISSUE THREAD

**Issue by Yufeikang** [haxpor/Potatso#63]
直接打包没法签名成功，修改了这几个文件里的bundle id
![image](https://user-images.githubusercontent.com/4519880/34675855-cd39a884-f4c5-11e7-9b2d-db6a261fa259.png)

应用启动后会在 这里闪退
![image](https://user-images.githubusercontent.com/4519880/34675785-9dcf0864-f4c5-11e7-9d33-188e69d5b9f5.png)

Thread 1: signal SIGABRT

请问 还有什么地方和 id关联还需要改的买

**Comment by haxpor** [comment]
Another one `Potatso.m` see [here](https://github.com/haxpor/Potatso/blob/master/PotatsoBase/Potatso.m#L17).

**Comment by Yufeikang** [comment]
解决了， Thanks @haxpor
