### ISSUE TITLE
I have add some protocol, but I don't know how to push it to github. 

### ISSUE THREAD

**Issue by zhkufish** [haxpor/Potatso#64]
"auth_sha1_v4",
"auth_aes128_md5",
"auth_aes128_sha1",  3 protocol had add in my clone project, and test, It's ok.  but shadowsocks-libev is a submodule. I don't know how to push it to my fork. "auth_chain_a", "auth_chain_b"  add too. but test failed.

**Comment by haxpor** [comment]
That's great to hear! Although we can push only what works first, and work out the less later.

Ok, for `shadowsocks-libev` as it lives as git submodule, you need to do following
- modify `.gitmodules` and change its `url` counterpart to updated repo
- sync and immediately update git submodules by executing
   ```
   git submodule sync
   git submodule update --init --recursive --remote
   ```
- Check at `Library/ShadowPath/ShadowPath/shadowsocks-libev` that it has actually updated version

**Note** I'm setting up travis right now, so I will notify you here when I'm ready for you to send PR so we could take benefit from automated checking & building before we could do real test.

**Comment by zhkufish** [comment]
I had pull a new requests. add 3 protocol and remove some not used pod.

**Comment by haxpor** [comment]
Sure, I left my feedback there.
