### ISSUE TITLE
大神 instagram 加载不全图片 ？文字有的时候也加载不了？

### ISSUE THREAD

**Issue by CoderJin** [haxpor/Potatso#67]

**Comment by haxpor** [comment]
Did you try setting up proxy rule like this?

![img_5895](https://user-images.githubusercontent.com/673757/34904251-2b7fbd42-f87d-11e7-9713-a2cf48977518.PNG)

**Comment by CoderJin** [comment]
![image](https://user-images.githubusercontent.com/18577384/34904307-4bf5f540-f87e-11e7-9d24-1fbaa20ba755.png)

**Comment by CoderJin** [comment]
No URL this type？

**Comment by haxpor** [comment]
Ohh, that rule I had long long time ago via cloudset (which is defunct now).
You can try this instead, it works on my end, apply to entire domain.

![img](https://user-images.githubusercontent.com/673757/34904363-66295532-f87f-11e7-9dca-3a364bacda5a.png)

**Comment by CoderJin** [comment]
还是不行啊

**Comment by haxpor** [comment]
also try to restart the app, close VPN connection and connect again...

**Comment by CoderJin** [comment]
我卸载后重新安装还是不行

**Comment by CoderJin** [comment]
![d3cd950c31b15076de4715c378e645c7](https://user-images.githubusercontent.com/18577384/34904544-e8dff050-f882-11e7-91f1-7310511ea219.png)
![1e1e2ee54b2aa6f4b2828a368f1361dd](https://user-images.githubusercontent.com/18577384/34904546-edb4b7a0-f882-11e7-8fb4-4271e72030b2.png)

**Comment by CoderJin** [comment]
你那边能正常加载成功不？

**Comment by haxpor** [comment]
@CoderJin I'm checking this.

**Comment by CoderJin** [comment]
domain_prefix
domain_keyword
domain_suffix
domain_complete

**Comment by CoderJin** [comment]
还有我看你那边有URL ，是否你那边没问题，可能你已经改完善了

**Comment by haxpor** [comment]
Fixed in 4ef3f1940c6dd2d7f58068bc3135337fcdd25385.
PS: I knew now why it might not work for everyone when we set up `DOMAIN` rule set. Because instagram makes requests outside of instagram.com domain as well. So `URL` type of rule set will help this.

**Comment by CoderJin** [comment]
messenger 你这个能正常连接不？好像也连接不上
