### ISSUE TITLE
messenger 连接不上？

### ISSUE THREAD

**Issue by CoderJin** [haxpor/Potatso#68]
![p 5 6qa yz5v4m1cn hx2a](https://user-images.githubusercontent.com/18577384/34943017-c7bcb3fa-fa34-11e7-9300-f2cd0c77d4d4.jpg) 
不知道大神有没有解决方案？

**Comment by haxpor** [comment]
@CoderJin Can you send message to your friend? or that "Connecting" status keeps showing but has no problem?

**Comment by CoderJin** [comment]
Can normally send a message, why always shows that the connection is in progress.

**Comment by haxpor** [comment]
I'm really not sure what's happening in case of facebook as well.
To work around and stop that "Connecting" spinning label, is to add URL proxy rule of `portal.fb.com*` with `REJECT`. Result of this won't show any status online, but will stop that spinning, instead it will show "Tap to connect to Internet".

As far as I know, I have no better solution right now.

**Comment by CoderJin** [comment]
Do not know if other people have encountered similar problems, it seems no one feedback on this issue?
