### ISSUE TITLE
似乎DNS应该分层，国内DNS解析国内，国外DNS解析国外，否则会导致淘宝天猫等软件封锁

### ISSUE THREAD

**Issue by aishuidedabai** [haxpor/Potatso#69]

**Comment by haxpor** [comment]
This is good suggestion! I do think it might solve some weird problem like #68 as it seems DNS is polluted.

What I see is similar to what shadowsocks-X-NG has about PAC and its gwlist. We might have something similar with smaller list to preserve battery.

Do you think similar? Please feel free to enlighten me on this topic, or give any advice on what approach/implementation we should be going. Thank you!

**Comment by aishuidedabai** [comment]
因为dns是递归查询，所以应该给dns做一个socks透明代理（不知potatso中的Antinat是否起到了这个作用），匹配国内ip段或者域名，采用精确和模糊匹配，所以这里的规则应该加上直连国内域名或者ip段用国内dns解析，另外还要注意上层DHCP分配dns的解析失败会被误认为是国外ip（偶发情况），所以这里至少应该写一个dns备份或者超时设置（个人认为备份dns比较好）
