### ISSUE TITLE
点击连接报错

### ISSUE THREAD

**Issue by samblabla** [haxpor/Potatso#72]
`-[NEVPNManager saveToPreferenc:337  Failed to save configuration: Error Domain=NEVPNErrorDomain Code=5 "failed to make changes in SCPreferences: (null)" UserInfo={NSLocalizedDescription=failed to make changes in SCPreferences: (null)}
`
![qq20180130-0](https://user-images.githubusercontent.com/3224632/35543985-efaf8e9a-05a2-11e8-8f03-1cb055e6e71c.jpg)

**Comment by CoderJin** [comment]
这是权限的问题 可以点击Capabilities  进行权限配置

**Comment by samblabla** [comment]
@CoderJin   Capabilities 里面的personal VPN ,Network Extensions我都有开的，没有用

**Comment by CoderJin** [comment]
group 换没

**Comment by samblabla** [comment]
@CoderJin group换了，不换的话整个 app都是空白的。

**Comment by samblabla** [comment]
解决了 https://forums.developer.apple.com/thread/17611
bundle identifier 必需带 .
