### ISSUE TITLE
Confidential.h file not found

### ISSUE THREAD

**Issue by ruchiragile** [haxpor/Potatso#8]
I've gone through the ReadMe file to install the required dependencies and installed those dependencies, however "Confidential.h" is still missing in the code with the error "Confidential.h file not found". Please provide the required file or steps to fix the issue.

**Comment by haxpor** [comment]
`Confidential.h` file will be generated automatically during build step.
You can see it here in Xcode.

![screen shot 2017-02-08 at 9 03 42 pm](https://cloud.githubusercontent.com/assets/673757/22738435/6acd5680-ee42-11e6-97c3-c429b1ae5af0.png)

I guess there might be something wrong or some places else you miss.
But all in all, please wait until I have time to fix #6 as it might lead you to error you reported.

I close this now, and later you can go back to #6 when it get fixed to try again :)
