### ISSUE TITLE
xcode9.3 build faile

### ISSUE THREAD

**Issue by Sky891028** [haxpor/Potatso#83]
Showing All Errors Only
potatso/Library/ShadowPath/ShadowPath/Privoxy/pcre/pcreposix.c:149:41: No member named 're_erroffset' in 'regex_t'

potatso/Library/ShadowPath/ShadowPath/Privoxy/pcre/pcreposix.c:155:65: No member named 're_erroffset' in 'regex_t'

potatso/Library/ShadowPath/ShadowPath/Privoxy/pcre/pcreposix.c:176:19: No member named 're_pcre' in 'regex_t'

potatso/Library/ShadowPath/ShadowPath/Privoxy/pcre/pcreposix.c:206:7: No member named 're_pcre' in 'regex_t'

potatso/Library/ShadowPath/ShadowPath/Privoxy/pcre/pcreposix.c:207:7: No member named 're_erroffset' in 'regex_t'

potatso/Library/ShadowPath/ShadowPath/Privoxy/pcre/pcreposix.c:209:11: No member named 're_pcre' in 'regex_t'

potatso/Library/ShadowPath/ShadowPath/Privoxy/pcre/pcreposix.c:211:33: No member named 're_pcre' in 'regex_t'

potatso/Library/ShadowPath/ShadowPath/Privoxy/pcre/pcreposix.c:238:7: No member named 're_erroffset' in 'regex_t'

potatso/Library/ShadowPath/ShadowPath/Privoxy/pcre/pcreposix.c:246:22: No member named 're_pcre' in 'regex_t'

**Comment by wangjinwei0806** [comment]
我有尝试注释掉pcreposix.c 部分错误提示 好像也能正常使用

**Comment by Leon998** [comment]
have same problem... need help

**Comment by Sky891028** [comment]
It's OK 
Do the follow changes 
=====
're_pcre' change to 're_g'
're_erroffset' change to 're_nsub'

Thanks @caobug

**Comment by NLSC** [comment]
Build Settings -> Apple LLVM 9.0 - Language - Modules, set "Enable Modules (C and Objective-C)" to "No"
