### ISSUE TITLE
Xcode 9.3 compile failed.

### ISSUE THREAD

**Issue by willbin** [haxpor/Potatso#86]
Do you guys have a plan to adapt Xcode 9.3?

**Comment by damonYuan** [comment]
I encounter the problem `.../Potatso/Library/ShadowPath/ShadowPath/shadowsocks-libev/libipset/set/inspection.c:11:10: 'libcork/core.h' file not found` in Xcode 9.3 as well.

**Comment by damonYuan** [comment]
`.../Potatso/Library/ShadowPath/ShadowPath/shadowsocks-libev/libipset/set/inspection.c:11:10: 'libcork/core.h' file not found` still happens in my build, how can I deal with it?
