### ISSUE TITLE
 expected submodule commit SHA in output of task

### ISSUE THREAD

**Issue by Hughen** [haxpor/Potatso#87]
I can not build this project in my computer.
I went through the following process, e.g:

1. `git submodule update --init`
2. `pod install`
3. `carthage update`

but 3 step has been failed:

*** Fetching YAML.framework
Parse error: expected submodule commit SHA in output of task (ls-tree -z HEAD Library/Eureka) but encountered:

**Comment by haxpor** [comment]
Thank you. It's my mistake of not removing [these lines](https://github.com/haxpor/Potatso/blob/master/.gitmodules#L7-L9) from .gitsubmodules.

I will fix this and push new update. In the meantime, you can fix this yourself by starting fresh, and removing those lines before execute commands.

**Comment by haxpor** [comment]
Ok, please also do `rm -rf .git/modules/Library/Eureka` and see if it helps.

**Comment by haxpor** [comment]
You need to **remove** cloned directory, edit that .gitmodules file then execute the command. It needs to start all over to make it works.

**Comment by haxpor** [comment]
You need to **remove** cloned directory, edit that .gitmodules file then execute the command. It needs to start all over to make it works.

**Comment by haxpor** [comment]
I pushed a new commit for this fix. You don't have to pull in but just follow above steps. If still encounter the problem, feel free to reopen. Thanks!
