### ISSUE TITLE
Save the time for other developers

### ISSUE THREAD

**Issue by damonYuan** [haxpor/Potatso#88]
I encounter the problem that

```
libcork/core.h not found
```
and cannot get it solved. I tried `Header Search Path`, `User Search Path`, manually add the header file into projects, etc. All do no help to this problem.

Finally today, I find the root cause is the file system. My Workspace is CaseSensitity file system because of some projects (normally c) require it, so I clone this project into that volume and this cause the error I mentioned above. 

I know there might not be so many developers will have a separate file system in one macbook but I put it here to save the trouble shotting time for others. Or better some one can add it in the README.md, just a single line: 

# DO NOT CLONE INTO CASE-SENSITIVE FILESYSTEM!!!

**Comment by haxpor** [comment]
Thank you @damonYuan !

For other that faces with this issue, please see [wiki](https://github.com/haxpor/Potatso/wiki/Bug-Report).
