### ISSUE TITLE
No podspec found

### ISSUE THREAD

**Issue by MrBenFTW** [haxpor/Potatso#89]
Terminal:

Bens-MBP:~ mrbenftw$ cd /Users/mrbenftw/Files/Potatso-master 
Bens-MBP:Potatso-master mrbenftw$ pod install
Analyzing dependencies
Fetching podspec for `Aspects` from `./Library/Aspects/`
Fetching podspec for `CallbackURLKit` from `./Library/CallbackURLKit`
[!] No podspec found for `CallbackURLKit` in `./Library/CallbackURLKit`
Bens-MBP:Potatso-master mrbenftw$

**Comment by haxpor** [comment]
Hi, did you follow along in [How to build](https://github.com/haxpor/Potatso#how-to-build-project)?

**Comment by MrBenFTW** [comment]
Terminal:

Bens-MBP:~ mrbenftw$ cd /Users/mrbenftw/Downloads/Potatso-master 
Bens-MBP:Potatso-master mrbenftw$ git submodule update --init
fatal: Not a git repository (or any of the parent directories): .git
Bens-MBP:Potatso-master mrbenftw$ cd /Users/mrbenftw/Downloads/Potatso-master 
Bens-MBP:Potatso-master mrbenftw$ git submodule update --init
fatal: Not a git repository (or any of the parent directories): .git
Bens-MBP:Potatso-master mrbenftw$ pod install
Analyzing dependencies
Fetching podspec for `Aspects` from `./Library/Aspects/`
Fetching podspec for `CallbackURLKit` from `./Library/CallbackURLKit`
[!] No podspec found for `CallbackURLKit` in `./Library/CallbackURLKit`
Bens-MBP:Potatso-master mrbenftw$

**Comment by haxpor** [comment]
Thanks MrBenFTW. Please do the following

* `git clone https://github.com/haxpor/Potatso.git` (or faster `git clone https://github.com/haxpor/Potatso.git --depth=1`
* `... follow along from README.md...`

The important is in step 1. I think you might just click to Download repository from github web interface. If do this, the repository will miss crucial information for gitsubmodule to be working. Unfortunately README.md file assume you clone the project via command line.

Anyway, let me know if this solves your problem. Thanks.

**Comment by MrBenFTW** [comment]
Hi, sorry for late reply. Will see now

**Comment by MrBenFTW** [comment]
Yep, that was the issue. Sorry for wasting time. It is fixed now ;)

**Comment by liushengnan** [comment]
I have followed along in [How to build](https://github.com/haxpor/Potatso#how-to-build-project).But still have error.  I find some library in github had not exist. Is or not??
Terminal:
   
liushengnandeMacBook-Pro:Downloads liushengnan$ git clone https://github.com/haxpor/Potatso.git
Cloning into 'Potatso'...
remote: Counting objects: 3444, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 3444 (delta 5), reused 20 (delta 3), pack-reused 3417
Receiving objects: 100% (3444/3444), 28.87 MiB | 37.00 KiB/s, done.
Resolving deltas: 100% (1784/1784), done.
liushengnandeMacBook-Pro:Downloads liushengnan$ cd Potatso/
liushengnandeMacBook-Pro:Potatso liushengnan$ git submodule update --init
Submodule 'Library/CallbackURLKit' (https://github.com/phimage/CallbackURLKit.git) registered for path 'Library/CallbackURLKit'
Submodule 'Library/ShadowPath/ShadowPath/libmaxminddb' (https://github.com/haxpor/libmaxminddb.git) registered for path 'Library/ShadowPath/ShadowPath/libmaxminddb'
Submodule 'Library/ShadowPath/ShadowPath/shadowsocks-libev' (https://github.com/icodesign/shadowsocks-libev.git) registered for path 'Library/ShadowPath/ShadowPath/shadowsocks-libev'
Cloning into '/Users/liushengnan/Downloads/Potatso/Library/CallbackURLKit'...
Cloning into '/Users/liushengnan/Downloads/Potatso/Library/ShadowPath/ShadowPath/libmaxminddb'...
Cloning into '/Users/liushengnan/Downloads/Potatso/Library/ShadowPath/ShadowPath/shadowsocks-libev'...
remote: Repository not found.
fatal: repository 'https://github.com/icodesign/shadowsocks-libev.git/' not found
fatal: clone of 'https://github.com/icodesign/shadowsocks-libev.git' into submodule path '/Users/liushengnan/Downloads/Potatso/Library/ShadowPath/ShadowPath/shadowsocks-libev' failed
Failed to clone 'Library/ShadowPath/ShadowPath/shadowsocks-libev'. Retry scheduled
Cloning into '/Users/liushengnan/Downloads/Potatso/Library/ShadowPath/ShadowPath/shadowsocks-libev'...
remote: Repository not found.
fatal: repository 'https://github.com/icodesign/shadowsocks-libev.git/' not found
fatal: clone of 'https://github.com/icodesign/shadowsocks-libev.git' into submodule path '/Users/liushengnan/Downloads/Potatso/Library/ShadowPath/ShadowPath/shadowsocks-libev' failed
Failed to clone 'Library/ShadowPath/ShadowPath/shadowsocks-libev' a second time, aborting
liushengnandeMacBook-Pro:Potatso liushengnan$

**Comment by haxpor** [comment]
@liushengnan I just checked, this is due to such library is not available on that url anymore. Solution for now is to put such source online from anyone that has hold of that lib. I'll fix it.

**Comment by haxpor** [comment]
@liushengnan fixed via https://github.com/haxpor/Potatso/commit/87ff60cd862e62e0c8cf1be76ecdd46c1423b68a. Please reclone the project again. Things should be fine now.

**Comment by liushengnan** [comment]
Installing Crashlytics (3.8.3)
  
[!] Error installing Crashlytics
[!] /usr/bin/curl -f -L -o /var/folders/7t/hw9153h15_l3v20ds2vnj89w0000gn/T/d20180528-45159-12xeb1m/file.zip https://kit-downloads.fabric.io/cocoapods/crashlytics/3.8.3/crashlytics.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:45 --:--:--     0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to kit-downloads.fabric.io:443
