### ISSUE TITLE
Pod installations failed

### ISSUE THREAD

**Issue by pramodios** [haxpor/Potatso#97]
following these steps to install Patatso :-
![screen shot 2018-06-30 at 15 23 38](https://user-images.githubusercontent.com/23394639/42124033-9ec787be-7c79-11e8-8e19-9e0de9e81cfb.png)

on step 4(pod install) error comes :-
![screen shot 2018-06-30 at 15 26 56](https://user-images.githubusercontent.com/23394639/42124067-1424178e-7c7a-11e8-8bcc-908ac7900920.png)

please help me how to solve this issue.

**Comment by haxpor** [comment]
This is most likely about network issue on your end which cannot download such file.
You might want to try again, or enable VPN or SS on machine you're executing this.

**Comment by pramodios** [comment]
thnkx
