### ISSUE TITLE
 pod install     [!] Error installing Crashlytics   

### ISSUE THREAD

**Issue by HAPENLY** [haxpor/Potatso#98]
#### 3. pod install 

I followed the steps to install the problem when I was running to pod install.

```
[!] Error installing Crashlytics
[!] /usr/bin/curl -f -L -o /var/folders/df/78n63m8s637ffyp78cclhtj00000gn/T/d20180702-27577-d1eegh/file.zip https://kit-downloads.fabric.io/cocoapods/crashlytics/3.7.3/crashlytics.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:04:01 --:--:--     0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to kit-downloads.fabric.io:443 

```

I use Pod version ` 1.5.3`

Can you tell me how to solve this problem, please!

**Comment by haxpor** [comment]
Similar to #97 From error log, it cannot download such file.
Try again with different network, or use VPN/Shadowsocks on system you executing such command.

**Comment by HAPENLY** [comment]
I solved this problem, it is time to turn on SS. Thank you.

**Comment by GuoZhiQiang** [comment]
For me , It's useful to update pod repo: `pod repo update`
